// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: cybermap.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Cybermap_Health_FullMethodName      = "/cybertele.Cybermap/Health"
	Cybermap_ParserState_FullMethodName = "/cybertele.Cybermap/ParserState"
	Cybermap_ParserStart_FullMethodName = "/cybertele.Cybermap/ParserStart"
	Cybermap_ParserStop_FullMethodName  = "/cybertele.Cybermap/ParserStop"
	Cybermap_ParserLogs_FullMethodName  = "/cybertele.Cybermap/ParserLogs"
	Cybermap_InRadius_FullMethodName    = "/cybertele.Cybermap/InRadius"
)

// CybermapClient is the client API for Cybermap service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CybermapClient interface {
	Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthReply, error)
	ParserState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ParserStatus, error)
	ParserStart(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ParserStatus, error)
	ParserStop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ParserStatus, error)
	ParserLogs(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*ParserMapLogsReply, error)
	InRadius(ctx context.Context, in *RadiusRequest, opts ...grpc.CallOption) (*MapReply, error)
}

type cybermapClient struct {
	cc grpc.ClientConnInterface
}

func NewCybermapClient(cc grpc.ClientConnInterface) CybermapClient {
	return &cybermapClient{cc}
}

func (c *cybermapClient) Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthReply)
	err := c.cc.Invoke(ctx, Cybermap_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cybermapClient) ParserState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ParserStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParserStatus)
	err := c.cc.Invoke(ctx, Cybermap_ParserState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cybermapClient) ParserStart(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ParserStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParserStatus)
	err := c.cc.Invoke(ctx, Cybermap_ParserStart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cybermapClient) ParserStop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ParserStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParserStatus)
	err := c.cc.Invoke(ctx, Cybermap_ParserStop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cybermapClient) ParserLogs(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*ParserMapLogsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParserMapLogsReply)
	err := c.cc.Invoke(ctx, Cybermap_ParserLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cybermapClient) InRadius(ctx context.Context, in *RadiusRequest, opts ...grpc.CallOption) (*MapReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MapReply)
	err := c.cc.Invoke(ctx, Cybermap_InRadius_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CybermapServer is the server API for Cybermap service.
// All implementations must embed UnimplementedCybermapServer
// for forward compatibility.
type CybermapServer interface {
	Health(context.Context, *Empty) (*HealthReply, error)
	ParserState(context.Context, *Empty) (*ParserStatus, error)
	ParserStart(context.Context, *Empty) (*ParserStatus, error)
	ParserStop(context.Context, *Empty) (*ParserStatus, error)
	ParserLogs(context.Context, *PageRequest) (*ParserMapLogsReply, error)
	InRadius(context.Context, *RadiusRequest) (*MapReply, error)
	mustEmbedUnimplementedCybermapServer()
}

// UnimplementedCybermapServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCybermapServer struct{}

func (UnimplementedCybermapServer) Health(context.Context, *Empty) (*HealthReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedCybermapServer) ParserState(context.Context, *Empty) (*ParserStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method ParserState not implemented")
}
func (UnimplementedCybermapServer) ParserStart(context.Context, *Empty) (*ParserStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method ParserStart not implemented")
}
func (UnimplementedCybermapServer) ParserStop(context.Context, *Empty) (*ParserStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method ParserStop not implemented")
}
func (UnimplementedCybermapServer) ParserLogs(context.Context, *PageRequest) (*ParserMapLogsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ParserLogs not implemented")
}
func (UnimplementedCybermapServer) InRadius(context.Context, *RadiusRequest) (*MapReply, error) {
	return nil, status.Error(codes.Unimplemented, "method InRadius not implemented")
}
func (UnimplementedCybermapServer) mustEmbedUnimplementedCybermapServer() {}
func (UnimplementedCybermapServer) testEmbeddedByValue()                  {}

// UnsafeCybermapServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CybermapServer will
// result in compilation errors.
type UnsafeCybermapServer interface {
	mustEmbedUnimplementedCybermapServer()
}

func RegisterCybermapServer(s grpc.ServiceRegistrar, srv CybermapServer) {
	// If the following call panics, it indicates UnimplementedCybermapServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Cybermap_ServiceDesc, srv)
}

func _Cybermap_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybermapServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cybermap_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybermapServer).Health(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cybermap_ParserState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybermapServer).ParserState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cybermap_ParserState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybermapServer).ParserState(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cybermap_ParserStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybermapServer).ParserStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cybermap_ParserStart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybermapServer).ParserStart(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cybermap_ParserStop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybermapServer).ParserStop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cybermap_ParserStop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybermapServer).ParserStop(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cybermap_ParserLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybermapServer).ParserLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cybermap_ParserLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybermapServer).ParserLogs(ctx, req.(*PageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cybermap_InRadius_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RadiusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybermapServer).InRadius(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cybermap_InRadius_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybermapServer).InRadius(ctx, req.(*RadiusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Cybermap_ServiceDesc is the grpc.ServiceDesc for Cybermap service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cybermap_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cybertele.Cybermap",
	HandlerType: (*CybermapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _Cybermap_Health_Handler,
		},
		{
			MethodName: "ParserState",
			Handler:    _Cybermap_ParserState_Handler,
		},
		{
			MethodName: "ParserStart",
			Handler:    _Cybermap_ParserStart_Handler,
		},
		{
			MethodName: "ParserStop",
			Handler:    _Cybermap_ParserStop_Handler,
		},
		{
			MethodName: "ParserLogs",
			Handler:    _Cybermap_ParserLogs_Handler,
		},
		{
			MethodName: "InRadius",
			Handler:    _Cybermap_InRadius_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cybermap.proto",
}
