// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: cybermap.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParserMapLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Errors        []string               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParserMapLog) Reset() {
	*x = ParserMapLog{}
	mi := &file_cybermap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParserMapLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParserMapLog) ProtoMessage() {}

func (x *ParserMapLog) ProtoReflect() protoreflect.Message {
	mi := &file_cybermap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParserMapLog.ProtoReflect.Descriptor instead.
func (*ParserMapLog) Descriptor() ([]byte, []int) {
	return file_cybermap_proto_rawDescGZIP(), []int{0}
}

func (x *ParserMapLog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ParserMapLog) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ParserMapLog) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ParserMapLog) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ParserMapLogsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*ParserMapLog        `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParserMapLogsReply) Reset() {
	*x = ParserMapLogsReply{}
	mi := &file_cybermap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParserMapLogsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParserMapLogsReply) ProtoMessage() {}

func (x *ParserMapLogsReply) ProtoReflect() protoreflect.Message {
	mi := &file_cybermap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParserMapLogsReply.ProtoReflect.Descriptor instead.
func (*ParserMapLogsReply) Descriptor() ([]byte, []int) {
	return file_cybermap_proto_rawDescGZIP(), []int{1}
}

func (x *ParserMapLogsReply) GetData() []*ParserMapLog {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ParserMapLogsReply) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type Geom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float32                `protobuf:"fixed32,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float32                `protobuf:"fixed32,2,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Geom) Reset() {
	*x = Geom{}
	mi := &file_cybermap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Geom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Geom) ProtoMessage() {}

func (x *Geom) ProtoReflect() protoreflect.Message {
	mi := &file_cybermap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Geom.ProtoReflect.Descriptor instead.
func (*Geom) Descriptor() ([]byte, []int) {
	return file_cybermap_proto_rawDescGZIP(), []int{2}
}

func (x *Geom) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Geom) GetLon() float32 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type RadiusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Center        *Geom                  `protobuf:"bytes,1,opt,name=center,proto3" json:"center,omitempty"`
	Radius        int32                  `protobuf:"varint,2,opt,name=radius,proto3" json:"radius,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RadiusRequest) Reset() {
	*x = RadiusRequest{}
	mi := &file_cybermap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RadiusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RadiusRequest) ProtoMessage() {}

func (x *RadiusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cybermap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RadiusRequest.ProtoReflect.Descriptor instead.
func (*RadiusRequest) Descriptor() ([]byte, []int) {
	return file_cybermap_proto_rawDescGZIP(), []int{3}
}

func (x *RadiusRequest) GetCenter() *Geom {
	if x != nil {
		return x.Center
	}
	return nil
}

func (x *RadiusRequest) GetRadius() int32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

type MapReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*MachineMapData      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapReply) Reset() {
	*x = MapReply{}
	mi := &file_cybermap_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapReply) ProtoMessage() {}

func (x *MapReply) ProtoReflect() protoreflect.Message {
	mi := &file_cybermap_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapReply.ProtoReflect.Descriptor instead.
func (*MapReply) Descriptor() ([]byte, []int) {
	return file_cybermap_proto_rawDescGZIP(), []int{4}
}

func (x *MapReply) GetData() []*MachineMapData {
	if x != nil {
		return x.Data
	}
	return nil
}

type MachineMapData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            int32                  `protobuf:"varint,1,opt,name=sn,proto3" json:"sn,omitempty"`
	Workhours     float32                `protobuf:"fixed32,2,opt,name=workhours,proto3" json:"workhours,omitempty"`
	Coords        *Geom                  `protobuf:"bytes,3,opt,name=coords,proto3" json:"coords,omitempty"`
	TimePoint     string                 `protobuf:"bytes,4,opt,name=timePoint,proto3" json:"timePoint,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineMapData) Reset() {
	*x = MachineMapData{}
	mi := &file_cybermap_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineMapData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineMapData) ProtoMessage() {}

func (x *MachineMapData) ProtoReflect() protoreflect.Message {
	mi := &file_cybermap_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineMapData.ProtoReflect.Descriptor instead.
func (*MachineMapData) Descriptor() ([]byte, []int) {
	return file_cybermap_proto_rawDescGZIP(), []int{5}
}

func (x *MachineMapData) GetSn() int32 {
	if x != nil {
		return x.Sn
	}
	return 0
}

func (x *MachineMapData) GetWorkhours() float32 {
	if x != nil {
		return x.Workhours
	}
	return 0
}

func (x *MachineMapData) GetCoords() *Geom {
	if x != nil {
		return x.Coords
	}
	return nil
}

func (x *MachineMapData) GetTimePoint() string {
	if x != nil {
		return x.TimePoint
	}
	return ""
}

func (x *MachineMapData) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_cybermap_proto protoreflect.FileDescriptor

const file_cybermap_proto_rawDesc = "" +
	"\n" +
	"\x0ecybermap.proto\x12\tcybertele\x1a\vcyber.proto\"j\n" +
	"\fParserMapLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors\x12\x1c\n" +
	"\tcreatedAt\x18\x04 \x01(\tR\tcreatedAt\"x\n" +
	"\x12ParserMapLogsReply\x12+\n" +
	"\x04data\x18\x01 \x03(\v2\x17.cybertele.ParserMapLogR\x04data\x125\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x15.cybertele.PaginationR\n" +
	"pagination\"*\n" +
	"\x04Geom\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x02R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x02R\x03lon\"P\n" +
	"\rRadiusRequest\x12'\n" +
	"\x06center\x18\x01 \x01(\v2\x0f.cybertele.GeomR\x06center\x12\x16\n" +
	"\x06radius\x18\x02 \x01(\x05R\x06radius\"9\n" +
	"\bMapReply\x12-\n" +
	"\x04data\x18\x01 \x03(\v2\x19.cybertele.MachineMapDataR\x04data\"\xa3\x01\n" +
	"\x0eMachineMapData\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\x05R\x02sn\x12\x1c\n" +
	"\tworkhours\x18\x02 \x01(\x02R\tworkhours\x12'\n" +
	"\x06coords\x18\x03 \x01(\v2\x0f.cybertele.GeomR\x06coords\x12\x1c\n" +
	"\ttimePoint\x18\x04 \x01(\tR\ttimePoint\x12\x1c\n" +
	"\tupdatedAt\x18\x05 \x01(\tR\tupdatedAt2\xbf\x03\n" +
	"\bCybermap\x124\n" +
	"\x06Health\x12\x10.cybertele.Empty\x1a\x16.cybertele.HealthReply\"\x00\x12:\n" +
	"\vParserState\x12\x10.cybertele.Empty\x1a\x17.cybertele.ParserStatus\"\x00\x12:\n" +
	"\vParserStart\x12\x10.cybertele.Empty\x1a\x17.cybertele.ParserStatus\"\x00\x129\n" +
	"\n" +
	"ParserStop\x12\x10.cybertele.Empty\x1a\x17.cybertele.ParserStatus\"\x00\x12E\n" +
	"\n" +
	"ParserLogs\x12\x16.cybertele.PageRequest\x1a\x1d.cybertele.ParserMapLogsReply\"\x00\x12F\n" +
	"\vMachineLogs\x12\x16.cybertele.PageRequest\x1a\x1d.cybertele.ParserMapLogsReply\"\x00\x12;\n" +
	"\bInRadius\x12\x18.cybertele.RadiusRequest\x1a\x13.cybertele.MapReply\"\x00B\tZ\a./protob\x06proto3"

var (
	file_cybermap_proto_rawDescOnce sync.Once
	file_cybermap_proto_rawDescData []byte
)

func file_cybermap_proto_rawDescGZIP() []byte {
	file_cybermap_proto_rawDescOnce.Do(func() {
		file_cybermap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cybermap_proto_rawDesc), len(file_cybermap_proto_rawDesc)))
	})
	return file_cybermap_proto_rawDescData
}

var file_cybermap_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cybermap_proto_goTypes = []any{
	(*ParserMapLog)(nil),       // 0: cybertele.ParserMapLog
	(*ParserMapLogsReply)(nil), // 1: cybertele.ParserMapLogsReply
	(*Geom)(nil),               // 2: cybertele.Geom
	(*RadiusRequest)(nil),      // 3: cybertele.RadiusRequest
	(*MapReply)(nil),           // 4: cybertele.MapReply
	(*MachineMapData)(nil),     // 5: cybertele.MachineMapData
	(*Pagination)(nil),         // 6: cybertele.Pagination
	(*Empty)(nil),              // 7: cybertele.Empty
	(*PageRequest)(nil),        // 8: cybertele.PageRequest
	(*HealthReply)(nil),        // 9: cybertele.HealthReply
	(*ParserStatus)(nil),       // 10: cybertele.ParserStatus
}
var file_cybermap_proto_depIdxs = []int32{
	0,  // 0: cybertele.ParserMapLogsReply.data:type_name -> cybertele.ParserMapLog
	6,  // 1: cybertele.ParserMapLogsReply.pagination:type_name -> cybertele.Pagination
	2,  // 2: cybertele.RadiusRequest.center:type_name -> cybertele.Geom
	5,  // 3: cybertele.MapReply.data:type_name -> cybertele.MachineMapData
	2,  // 4: cybertele.MachineMapData.coords:type_name -> cybertele.Geom
	7,  // 5: cybertele.Cybermap.Health:input_type -> cybertele.Empty
	7,  // 6: cybertele.Cybermap.ParserState:input_type -> cybertele.Empty
	7,  // 7: cybertele.Cybermap.ParserStart:input_type -> cybertele.Empty
	7,  // 8: cybertele.Cybermap.ParserStop:input_type -> cybertele.Empty
	8,  // 9: cybertele.Cybermap.ParserLogs:input_type -> cybertele.PageRequest
	8,  // 10: cybertele.Cybermap.MachineLogs:input_type -> cybertele.PageRequest
	3,  // 11: cybertele.Cybermap.InRadius:input_type -> cybertele.RadiusRequest
	9,  // 12: cybertele.Cybermap.Health:output_type -> cybertele.HealthReply
	10, // 13: cybertele.Cybermap.ParserState:output_type -> cybertele.ParserStatus
	10, // 14: cybertele.Cybermap.ParserStart:output_type -> cybertele.ParserStatus
	10, // 15: cybertele.Cybermap.ParserStop:output_type -> cybertele.ParserStatus
	1,  // 16: cybertele.Cybermap.ParserLogs:output_type -> cybertele.ParserMapLogsReply
	1,  // 17: cybertele.Cybermap.MachineLogs:output_type -> cybertele.ParserMapLogsReply
	4,  // 18: cybertele.Cybermap.InRadius:output_type -> cybertele.MapReply
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_cybermap_proto_init() }
func file_cybermap_proto_init() {
	if File_cybermap_proto != nil {
		return
	}
	file_cyber_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cybermap_proto_rawDesc), len(file_cybermap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cybermap_proto_goTypes,
		DependencyIndexes: file_cybermap_proto_depIdxs,
		MessageInfos:      file_cybermap_proto_msgTypes,
	}.Build()
	File_cybermap_proto = out.File
	file_cybermap_proto_goTypes = nil
	file_cybermap_proto_depIdxs = nil
}
