// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: cybermetrica.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParserMetricaLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sn            int32                  `protobuf:"varint,2,opt,name=sn,proto3" json:"sn,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	StartAt       string                 `protobuf:"bytes,4,opt,name=startAt,proto3" json:"startAt,omitempty"`
	EndAt         string                 `protobuf:"bytes,5,opt,name=endAt,proto3" json:"endAt,omitempty"`
	Errors        []string               `protobuf:"bytes,6,rep,name=errors,proto3" json:"errors,omitempty"`
	DataTypes     []string               `protobuf:"bytes,7,rep,name=dataTypes,proto3" json:"dataTypes,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParserMetricaLog) Reset() {
	*x = ParserMetricaLog{}
	mi := &file_cybermetrica_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParserMetricaLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParserMetricaLog) ProtoMessage() {}

func (x *ParserMetricaLog) ProtoReflect() protoreflect.Message {
	mi := &file_cybermetrica_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParserMetricaLog.ProtoReflect.Descriptor instead.
func (*ParserMetricaLog) Descriptor() ([]byte, []int) {
	return file_cybermetrica_proto_rawDescGZIP(), []int{0}
}

func (x *ParserMetricaLog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ParserMetricaLog) GetSn() int32 {
	if x != nil {
		return x.Sn
	}
	return 0
}

func (x *ParserMetricaLog) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ParserMetricaLog) GetStartAt() string {
	if x != nil {
		return x.StartAt
	}
	return ""
}

func (x *ParserMetricaLog) GetEndAt() string {
	if x != nil {
		return x.EndAt
	}
	return ""
}

func (x *ParserMetricaLog) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ParserMetricaLog) GetDataTypes() []string {
	if x != nil {
		return x.DataTypes
	}
	return nil
}

func (x *ParserMetricaLog) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ParserMetricaLogsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*ParserMetricaLog    `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParserMetricaLogsReply) Reset() {
	*x = ParserMetricaLogsReply{}
	mi := &file_cybermetrica_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParserMetricaLogsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParserMetricaLogsReply) ProtoMessage() {}

func (x *ParserMetricaLogsReply) ProtoReflect() protoreflect.Message {
	mi := &file_cybermetrica_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParserMetricaLogsReply.ProtoReflect.Descriptor instead.
func (*ParserMetricaLogsReply) Descriptor() ([]byte, []int) {
	return file_cybermetrica_proto_rawDescGZIP(), []int{1}
}

func (x *ParserMetricaLogsReply) GetData() []*ParserMetricaLog {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ParserMetricaLogsReply) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type MachineDataType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataType      *DataType              `protobuf:"bytes,1,opt,name=dataType,proto3" json:"dataType,omitempty"`
	LastDataTime  string                 `protobuf:"bytes,2,opt,name=lastDataTime,proto3" json:"lastDataTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineDataType) Reset() {
	*x = MachineDataType{}
	mi := &file_cybermetrica_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineDataType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineDataType) ProtoMessage() {}

func (x *MachineDataType) ProtoReflect() protoreflect.Message {
	mi := &file_cybermetrica_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineDataType.ProtoReflect.Descriptor instead.
func (*MachineDataType) Descriptor() ([]byte, []int) {
	return file_cybermetrica_proto_rawDescGZIP(), []int{2}
}

func (x *MachineDataType) GetDataType() *DataType {
	if x != nil {
		return x.DataType
	}
	return nil
}

func (x *MachineDataType) GetLastDataTime() string {
	if x != nil {
		return x.LastDataTime
	}
	return ""
}

type MachineDataTypesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*MachineDataType     `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineDataTypesReply) Reset() {
	*x = MachineDataTypesReply{}
	mi := &file_cybermetrica_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineDataTypesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineDataTypesReply) ProtoMessage() {}

func (x *MachineDataTypesReply) ProtoReflect() protoreflect.Message {
	mi := &file_cybermetrica_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineDataTypesReply.ProtoReflect.Descriptor instead.
func (*MachineDataTypesReply) Descriptor() ([]byte, []int) {
	return file_cybermetrica_proto_rawDescGZIP(), []int{3}
}

func (x *MachineDataTypesReply) GetData() []*MachineDataType {
	if x != nil {
		return x.Data
	}
	return nil
}

type MachineStatisticRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            int32                  `protobuf:"varint,1,opt,name=sn,proto3" json:"sn,omitempty"`
	Timezone      int32                  `protobuf:"varint,2,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	From          string                 `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	Graph         string                 `protobuf:"bytes,6,opt,name=graph,proto3" json:"graph,omitempty"`
	Code          float32                `protobuf:"fixed32,7,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineStatisticRequest) Reset() {
	*x = MachineStatisticRequest{}
	mi := &file_cybermetrica_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineStatisticRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineStatisticRequest) ProtoMessage() {}

func (x *MachineStatisticRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cybermetrica_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineStatisticRequest.ProtoReflect.Descriptor instead.
func (*MachineStatisticRequest) Descriptor() ([]byte, []int) {
	return file_cybermetrica_proto_rawDescGZIP(), []int{4}
}

func (x *MachineStatisticRequest) GetSn() int32 {
	if x != nil {
		return x.Sn
	}
	return 0
}

func (x *MachineStatisticRequest) GetTimezone() int32 {
	if x != nil {
		return x.Timezone
	}
	return 0
}

func (x *MachineStatisticRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *MachineStatisticRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *MachineStatisticRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *MachineStatisticRequest) GetGraph() string {
	if x != nil {
		return x.Graph
	}
	return ""
}

func (x *MachineStatisticRequest) GetCode() float32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type DaysData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*DayData             `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaysData) Reset() {
	*x = DaysData{}
	mi := &file_cybermetrica_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaysData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaysData) ProtoMessage() {}

func (x *DaysData) ProtoReflect() protoreflect.Message {
	mi := &file_cybermetrica_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaysData.ProtoReflect.Descriptor instead.
func (*DaysData) Descriptor() ([]byte, []int) {
	return file_cybermetrica_proto_rawDescGZIP(), []int{5}
}

func (x *DaysData) GetData() []*DayData {
	if x != nil {
		return x.Data
	}
	return nil
}

type DayData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            int32                  `protobuf:"varint,1,opt,name=sn,proto3" json:"sn,omitempty"`
	Timezone      int32                  `protobuf:"varint,2,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Connection    *DayDataValues         `protobuf:"bytes,4,opt,name=connection,proto3" json:"connection,omitempty"`
	Workhours     *DayDataValues         `protobuf:"bytes,5,opt,name=workhours,proto3" json:"workhours,omitempty"`
	Engine        *DayDataValues         `protobuf:"bytes,6,opt,name=engine,proto3" json:"engine,omitempty"`
	Job           *DayDataValues         `protobuf:"bytes,7,opt,name=job,proto3" json:"job,omitempty"`
	HasErrors     bool                   `protobuf:"varint,8,opt,name=hasErrors,proto3" json:"hasErrors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DayData) Reset() {
	*x = DayData{}
	mi := &file_cybermetrica_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DayData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayData) ProtoMessage() {}

func (x *DayData) ProtoReflect() protoreflect.Message {
	mi := &file_cybermetrica_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayData.ProtoReflect.Descriptor instead.
func (*DayData) Descriptor() ([]byte, []int) {
	return file_cybermetrica_proto_rawDescGZIP(), []int{6}
}

func (x *DayData) GetSn() int32 {
	if x != nil {
		return x.Sn
	}
	return 0
}

func (x *DayData) GetTimezone() int32 {
	if x != nil {
		return x.Timezone
	}
	return 0
}

func (x *DayData) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DayData) GetConnection() *DayDataValues {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *DayData) GetWorkhours() *DayDataValues {
	if x != nil {
		return x.Workhours
	}
	return nil
}

func (x *DayData) GetEngine() *DayDataValues {
	if x != nil {
		return x.Engine
	}
	return nil
}

func (x *DayData) GetJob() *DayDataValues {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *DayData) GetHasErrors() bool {
	if x != nil {
		return x.HasErrors
	}
	return false
}

type DayDataValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         string                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           string                 `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	Duration      int64                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Min           float32                `protobuf:"fixed32,4,opt,name=min,proto3" json:"min,omitempty"`
	Max           float32                `protobuf:"fixed32,5,opt,name=max,proto3" json:"max,omitempty"`
	Value         float32                `protobuf:"fixed32,6,opt,name=value,proto3" json:"value,omitempty"`
	Blocks        []*BlockValue          `protobuf:"bytes,7,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DayDataValues) Reset() {
	*x = DayDataValues{}
	mi := &file_cybermetrica_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DayDataValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayDataValues) ProtoMessage() {}

func (x *DayDataValues) ProtoReflect() protoreflect.Message {
	mi := &file_cybermetrica_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayDataValues.ProtoReflect.Descriptor instead.
func (*DayDataValues) Descriptor() ([]byte, []int) {
	return file_cybermetrica_proto_rawDescGZIP(), []int{7}
}

func (x *DayDataValues) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *DayDataValues) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *DayDataValues) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *DayDataValues) GetMin() float32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *DayDataValues) GetMax() float32 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *DayDataValues) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *DayDataValues) GetBlocks() []*BlockValue {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type BlockValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         string                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           string                 `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	StartUnix     int64                  `protobuf:"varint,3,opt,name=startUnix,proto3" json:"startUnix,omitempty"`
	EndUnix       int64                  `protobuf:"varint,4,opt,name=endUnix,proto3" json:"endUnix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockValue) Reset() {
	*x = BlockValue{}
	mi := &file_cybermetrica_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockValue) ProtoMessage() {}

func (x *BlockValue) ProtoReflect() protoreflect.Message {
	mi := &file_cybermetrica_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockValue.ProtoReflect.Descriptor instead.
func (*BlockValue) Descriptor() ([]byte, []int) {
	return file_cybermetrica_proto_rawDescGZIP(), []int{8}
}

func (x *BlockValue) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *BlockValue) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *BlockValue) GetStartUnix() int64 {
	if x != nil {
		return x.StartUnix
	}
	return 0
}

func (x *BlockValue) GetEndUnix() int64 {
	if x != nil {
		return x.EndUnix
	}
	return 0
}

type MachineErrorsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errors        []*MachineError        `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineErrorsReply) Reset() {
	*x = MachineErrorsReply{}
	mi := &file_cybermetrica_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineErrorsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineErrorsReply) ProtoMessage() {}

func (x *MachineErrorsReply) ProtoReflect() protoreflect.Message {
	mi := &file_cybermetrica_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineErrorsReply.ProtoReflect.Descriptor instead.
func (*MachineErrorsReply) Descriptor() ([]byte, []int) {
	return file_cybermetrica_proto_rawDescGZIP(), []int{9}
}

func (x *MachineErrorsReply) GetErrors() []*MachineError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type MachineError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          float32                `protobuf:"fixed32,1,opt,name=code,proto3" json:"code,omitempty"`
	Blocks        []*MachineErrorBlock   `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineError) Reset() {
	*x = MachineError{}
	mi := &file_cybermetrica_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineError) ProtoMessage() {}

func (x *MachineError) ProtoReflect() protoreflect.Message {
	mi := &file_cybermetrica_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineError.ProtoReflect.Descriptor instead.
func (*MachineError) Descriptor() ([]byte, []int) {
	return file_cybermetrica_proto_rawDescGZIP(), []int{10}
}

func (x *MachineError) GetCode() float32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MachineError) GetBlocks() []*MachineErrorBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type MachineErrorBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         string                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           string                 `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	StartUnix     int64                  `protobuf:"varint,3,opt,name=startUnix,proto3" json:"startUnix,omitempty"`
	EndUnix       int64                  `protobuf:"varint,4,opt,name=endUnix,proto3" json:"endUnix,omitempty"`
	Code          float32                `protobuf:"fixed32,5,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineErrorBlock) Reset() {
	*x = MachineErrorBlock{}
	mi := &file_cybermetrica_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineErrorBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineErrorBlock) ProtoMessage() {}

func (x *MachineErrorBlock) ProtoReflect() protoreflect.Message {
	mi := &file_cybermetrica_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineErrorBlock.ProtoReflect.Descriptor instead.
func (*MachineErrorBlock) Descriptor() ([]byte, []int) {
	return file_cybermetrica_proto_rawDescGZIP(), []int{11}
}

func (x *MachineErrorBlock) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *MachineErrorBlock) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *MachineErrorBlock) GetStartUnix() int64 {
	if x != nil {
		return x.StartUnix
	}
	return 0
}

func (x *MachineErrorBlock) GetEndUnix() int64 {
	if x != nil {
		return x.EndUnix
	}
	return 0
}

func (x *MachineErrorBlock) GetCode() float32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type GraphData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           float32                `protobuf:"fixed32,1,opt,name=min,proto3" json:"min,omitempty"`
	Max           float32                `protobuf:"fixed32,2,opt,name=max,proto3" json:"max,omitempty"`
	Value         float32                `protobuf:"fixed32,3,opt,name=value,proto3" json:"value,omitempty"`
	Blocks        []*GraphBlockValues    `protobuf:"bytes,4,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphData) Reset() {
	*x = GraphData{}
	mi := &file_cybermetrica_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphData) ProtoMessage() {}

func (x *GraphData) ProtoReflect() protoreflect.Message {
	mi := &file_cybermetrica_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphData.ProtoReflect.Descriptor instead.
func (*GraphData) Descriptor() ([]byte, []int) {
	return file_cybermetrica_proto_rawDescGZIP(), []int{12}
}

func (x *GraphData) GetMin() float32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *GraphData) GetMax() float32 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *GraphData) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *GraphData) GetBlocks() []*GraphBlockValues {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type GraphBlockValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         string                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           string                 `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	StartUnix     int64                  `protobuf:"varint,3,opt,name=startUnix,proto3" json:"startUnix,omitempty"`
	EndUnix       int64                  `protobuf:"varint,4,opt,name=endUnix,proto3" json:"endUnix,omitempty"`
	RawData       []*RawItem             `protobuf:"bytes,5,rep,name=rawData,proto3" json:"rawData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphBlockValues) Reset() {
	*x = GraphBlockValues{}
	mi := &file_cybermetrica_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphBlockValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphBlockValues) ProtoMessage() {}

func (x *GraphBlockValues) ProtoReflect() protoreflect.Message {
	mi := &file_cybermetrica_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphBlockValues.ProtoReflect.Descriptor instead.
func (*GraphBlockValues) Descriptor() ([]byte, []int) {
	return file_cybermetrica_proto_rawDescGZIP(), []int{13}
}

func (x *GraphBlockValues) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *GraphBlockValues) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *GraphBlockValues) GetStartUnix() int64 {
	if x != nil {
		return x.StartUnix
	}
	return 0
}

func (x *GraphBlockValues) GetEndUnix() int64 {
	if x != nil {
		return x.EndUnix
	}
	return 0
}

func (x *GraphBlockValues) GetRawData() []*RawItem {
	if x != nil {
		return x.RawData
	}
	return nil
}

type RawItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          int64                  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Value         float32                `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawItem) Reset() {
	*x = RawItem{}
	mi := &file_cybermetrica_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawItem) ProtoMessage() {}

func (x *RawItem) ProtoReflect() protoreflect.Message {
	mi := &file_cybermetrica_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawItem.ProtoReflect.Descriptor instead.
func (*RawItem) Descriptor() ([]byte, []int) {
	return file_cybermetrica_proto_rawDescGZIP(), []int{14}
}

func (x *RawItem) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *RawItem) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_cybermetrica_proto protoreflect.FileDescriptor

const file_cybermetrica_proto_rawDesc = "" +
	"\n" +
	"\x12cybermetrica.proto\x12\tcybertele\x1a\vcyber.proto\"\xcc\x01\n" +
	"\x10ParserMetricaLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x0e\n" +
	"\x02sn\x18\x02 \x01(\x05R\x02sn\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12\x18\n" +
	"\astartAt\x18\x04 \x01(\tR\astartAt\x12\x14\n" +
	"\x05endAt\x18\x05 \x01(\tR\x05endAt\x12\x16\n" +
	"\x06errors\x18\x06 \x03(\tR\x06errors\x12\x1c\n" +
	"\tdataTypes\x18\a \x03(\tR\tdataTypes\x12\x1c\n" +
	"\tcreatedAt\x18\b \x01(\tR\tcreatedAt\"\x80\x01\n" +
	"\x16ParserMetricaLogsReply\x12/\n" +
	"\x04data\x18\x01 \x03(\v2\x1b.cybertele.ParserMetricaLogR\x04data\x125\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x15.cybertele.PaginationR\n" +
	"pagination\"f\n" +
	"\x0fMachineDataType\x12/\n" +
	"\bdataType\x18\x01 \x01(\v2\x13.cybertele.DataTypeR\bdataType\x12\"\n" +
	"\flastDataTime\x18\x02 \x01(\tR\flastDataTime\"G\n" +
	"\x15MachineDataTypesReply\x12.\n" +
	"\x04data\x18\x01 \x03(\v2\x1a.cybertele.MachineDataTypeR\x04data\"\xa7\x01\n" +
	"\x17MachineStatisticRequest\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\x05R\x02sn\x12\x1a\n" +
	"\btimezone\x18\x02 \x01(\x05R\btimezone\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x12\n" +
	"\x04from\x18\x04 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x05 \x01(\tR\x02to\x12\x14\n" +
	"\x05graph\x18\x06 \x01(\tR\x05graph\x12\x12\n" +
	"\x04code\x18\a \x01(\x02R\x04code\"2\n" +
	"\bDaysData\x12&\n" +
	"\x04data\x18\x01 \x03(\v2\x12.cybertele.DayDataR\x04data\"\xb7\x02\n" +
	"\aDayData\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\x05R\x02sn\x12\x1a\n" +
	"\btimezone\x18\x02 \x01(\x05R\btimezone\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x128\n" +
	"\n" +
	"connection\x18\x04 \x01(\v2\x18.cybertele.DayDataValuesR\n" +
	"connection\x126\n" +
	"\tworkhours\x18\x05 \x01(\v2\x18.cybertele.DayDataValuesR\tworkhours\x120\n" +
	"\x06engine\x18\x06 \x01(\v2\x18.cybertele.DayDataValuesR\x06engine\x12*\n" +
	"\x03job\x18\a \x01(\v2\x18.cybertele.DayDataValuesR\x03job\x12\x1c\n" +
	"\thasErrors\x18\b \x01(\bR\thasErrors\"\xbc\x01\n" +
	"\rDayDataValues\x12\x14\n" +
	"\x05start\x18\x01 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\tR\x03end\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x03R\bduration\x12\x10\n" +
	"\x03min\x18\x04 \x01(\x02R\x03min\x12\x10\n" +
	"\x03max\x18\x05 \x01(\x02R\x03max\x12\x14\n" +
	"\x05value\x18\x06 \x01(\x02R\x05value\x12-\n" +
	"\x06blocks\x18\a \x03(\v2\x15.cybertele.BlockValueR\x06blocks\"l\n" +
	"\n" +
	"BlockValue\x12\x14\n" +
	"\x05start\x18\x01 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\tR\x03end\x12\x1c\n" +
	"\tstartUnix\x18\x03 \x01(\x03R\tstartUnix\x12\x18\n" +
	"\aendUnix\x18\x04 \x01(\x03R\aendUnix\"E\n" +
	"\x12MachineErrorsReply\x12/\n" +
	"\x06errors\x18\x01 \x03(\v2\x17.cybertele.MachineErrorR\x06errors\"X\n" +
	"\fMachineError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x02R\x04code\x124\n" +
	"\x06blocks\x18\x02 \x03(\v2\x1c.cybertele.MachineErrorBlockR\x06blocks\"\x87\x01\n" +
	"\x11MachineErrorBlock\x12\x14\n" +
	"\x05start\x18\x01 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\tR\x03end\x12\x1c\n" +
	"\tstartUnix\x18\x03 \x01(\x03R\tstartUnix\x12\x18\n" +
	"\aendUnix\x18\x04 \x01(\x03R\aendUnix\x12\x12\n" +
	"\x04code\x18\x05 \x01(\x02R\x04code\"z\n" +
	"\tGraphData\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x02R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x02R\x03max\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x02R\x05value\x123\n" +
	"\x06blocks\x18\x04 \x03(\v2\x1b.cybertele.GraphBlockValuesR\x06blocks\"\xa0\x01\n" +
	"\x10GraphBlockValues\x12\x14\n" +
	"\x05start\x18\x01 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\tR\x03end\x12\x1c\n" +
	"\tstartUnix\x18\x03 \x01(\x03R\tstartUnix\x12\x18\n" +
	"\aendUnix\x18\x04 \x01(\x03R\aendUnix\x12,\n" +
	"\arawData\x18\x05 \x03(\v2\x12.cybertele.RawItemR\arawData\"3\n" +
	"\aRawItem\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x03R\x04time\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value2\x99\x06\n" +
	"\fCybermetrica\x124\n" +
	"\x06Health\x12\x10.cybertele.Empty\x1a\x16.cybertele.HealthReply\"\x00\x12:\n" +
	"\vParserState\x12\x10.cybertele.Empty\x1a\x17.cybertele.ParserStatus\"\x00\x12:\n" +
	"\vParserStart\x12\x10.cybertele.Empty\x1a\x17.cybertele.ParserStatus\"\x00\x129\n" +
	"\n" +
	"ParserStop\x12\x10.cybertele.Empty\x1a\x17.cybertele.ParserStatus\"\x00\x12I\n" +
	"\n" +
	"ParserLogs\x12\x16.cybertele.PageRequest\x1a!.cybertele.ParserMetricaLogsReply\"\x00\x12J\n" +
	"\vMachineLogs\x12\x16.cybertele.PageRequest\x1a!.cybertele.ParserMetricaLogsReply\"\x00\x12J\n" +
	"\x10MachineDataTypes\x12\x12.cybertele.Machine\x1a .cybertele.MachineDataTypesReply\"\x00\x12O\n" +
	"\x13MachineDayStatistic\x12\".cybertele.MachineStatisticRequest\x1a\x12.cybertele.DayData\"\x00\x12Q\n" +
	"\x14MachineDaysStatistic\x12\".cybertele.MachineStatisticRequest\x1a\x13.cybertele.DaysData\"\x00\x12T\n" +
	"\rMachineErrors\x12\".cybertele.MachineStatisticRequest\x1a\x1d.cybertele.MachineErrorsReply\"\x00\x12C\n" +
	"\x05Graph\x12\".cybertele.MachineStatisticRequest\x1a\x14.cybertele.GraphData\"\x00B\tZ\a./protob\x06proto3"

var (
	file_cybermetrica_proto_rawDescOnce sync.Once
	file_cybermetrica_proto_rawDescData []byte
)

func file_cybermetrica_proto_rawDescGZIP() []byte {
	file_cybermetrica_proto_rawDescOnce.Do(func() {
		file_cybermetrica_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cybermetrica_proto_rawDesc), len(file_cybermetrica_proto_rawDesc)))
	})
	return file_cybermetrica_proto_rawDescData
}

var file_cybermetrica_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_cybermetrica_proto_goTypes = []any{
	(*ParserMetricaLog)(nil),        // 0: cybertele.ParserMetricaLog
	(*ParserMetricaLogsReply)(nil),  // 1: cybertele.ParserMetricaLogsReply
	(*MachineDataType)(nil),         // 2: cybertele.MachineDataType
	(*MachineDataTypesReply)(nil),   // 3: cybertele.MachineDataTypesReply
	(*MachineStatisticRequest)(nil), // 4: cybertele.MachineStatisticRequest
	(*DaysData)(nil),                // 5: cybertele.DaysData
	(*DayData)(nil),                 // 6: cybertele.DayData
	(*DayDataValues)(nil),           // 7: cybertele.DayDataValues
	(*BlockValue)(nil),              // 8: cybertele.BlockValue
	(*MachineErrorsReply)(nil),      // 9: cybertele.MachineErrorsReply
	(*MachineError)(nil),            // 10: cybertele.MachineError
	(*MachineErrorBlock)(nil),       // 11: cybertele.MachineErrorBlock
	(*GraphData)(nil),               // 12: cybertele.GraphData
	(*GraphBlockValues)(nil),        // 13: cybertele.GraphBlockValues
	(*RawItem)(nil),                 // 14: cybertele.RawItem
	(*Pagination)(nil),              // 15: cybertele.Pagination
	(*DataType)(nil),                // 16: cybertele.DataType
	(*Empty)(nil),                   // 17: cybertele.Empty
	(*PageRequest)(nil),             // 18: cybertele.PageRequest
	(*Machine)(nil),                 // 19: cybertele.Machine
	(*HealthReply)(nil),             // 20: cybertele.HealthReply
	(*ParserStatus)(nil),            // 21: cybertele.ParserStatus
}
var file_cybermetrica_proto_depIdxs = []int32{
	0,  // 0: cybertele.ParserMetricaLogsReply.data:type_name -> cybertele.ParserMetricaLog
	15, // 1: cybertele.ParserMetricaLogsReply.pagination:type_name -> cybertele.Pagination
	16, // 2: cybertele.MachineDataType.dataType:type_name -> cybertele.DataType
	2,  // 3: cybertele.MachineDataTypesReply.data:type_name -> cybertele.MachineDataType
	6,  // 4: cybertele.DaysData.data:type_name -> cybertele.DayData
	7,  // 5: cybertele.DayData.connection:type_name -> cybertele.DayDataValues
	7,  // 6: cybertele.DayData.workhours:type_name -> cybertele.DayDataValues
	7,  // 7: cybertele.DayData.engine:type_name -> cybertele.DayDataValues
	7,  // 8: cybertele.DayData.job:type_name -> cybertele.DayDataValues
	8,  // 9: cybertele.DayDataValues.blocks:type_name -> cybertele.BlockValue
	10, // 10: cybertele.MachineErrorsReply.errors:type_name -> cybertele.MachineError
	11, // 11: cybertele.MachineError.blocks:type_name -> cybertele.MachineErrorBlock
	13, // 12: cybertele.GraphData.blocks:type_name -> cybertele.GraphBlockValues
	14, // 13: cybertele.GraphBlockValues.rawData:type_name -> cybertele.RawItem
	17, // 14: cybertele.Cybermetrica.Health:input_type -> cybertele.Empty
	17, // 15: cybertele.Cybermetrica.ParserState:input_type -> cybertele.Empty
	17, // 16: cybertele.Cybermetrica.ParserStart:input_type -> cybertele.Empty
	17, // 17: cybertele.Cybermetrica.ParserStop:input_type -> cybertele.Empty
	18, // 18: cybertele.Cybermetrica.ParserLogs:input_type -> cybertele.PageRequest
	18, // 19: cybertele.Cybermetrica.MachineLogs:input_type -> cybertele.PageRequest
	19, // 20: cybertele.Cybermetrica.MachineDataTypes:input_type -> cybertele.Machine
	4,  // 21: cybertele.Cybermetrica.MachineDayStatistic:input_type -> cybertele.MachineStatisticRequest
	4,  // 22: cybertele.Cybermetrica.MachineDaysStatistic:input_type -> cybertele.MachineStatisticRequest
	4,  // 23: cybertele.Cybermetrica.MachineErrors:input_type -> cybertele.MachineStatisticRequest
	4,  // 24: cybertele.Cybermetrica.Graph:input_type -> cybertele.MachineStatisticRequest
	20, // 25: cybertele.Cybermetrica.Health:output_type -> cybertele.HealthReply
	21, // 26: cybertele.Cybermetrica.ParserState:output_type -> cybertele.ParserStatus
	21, // 27: cybertele.Cybermetrica.ParserStart:output_type -> cybertele.ParserStatus
	21, // 28: cybertele.Cybermetrica.ParserStop:output_type -> cybertele.ParserStatus
	1,  // 29: cybertele.Cybermetrica.ParserLogs:output_type -> cybertele.ParserMetricaLogsReply
	1,  // 30: cybertele.Cybermetrica.MachineLogs:output_type -> cybertele.ParserMetricaLogsReply
	3,  // 31: cybertele.Cybermetrica.MachineDataTypes:output_type -> cybertele.MachineDataTypesReply
	6,  // 32: cybertele.Cybermetrica.MachineDayStatistic:output_type -> cybertele.DayData
	5,  // 33: cybertele.Cybermetrica.MachineDaysStatistic:output_type -> cybertele.DaysData
	9,  // 34: cybertele.Cybermetrica.MachineErrors:output_type -> cybertele.MachineErrorsReply
	12, // 35: cybertele.Cybermetrica.Graph:output_type -> cybertele.GraphData
	25, // [25:36] is the sub-list for method output_type
	14, // [14:25] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_cybermetrica_proto_init() }
func file_cybermetrica_proto_init() {
	if File_cybermetrica_proto != nil {
		return
	}
	file_cyber_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cybermetrica_proto_rawDesc), len(file_cybermetrica_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cybermetrica_proto_goTypes,
		DependencyIndexes: file_cybermetrica_proto_depIdxs,
		MessageInfos:      file_cybermetrica_proto_msgTypes,
	}.Build()
	File_cybermetrica_proto = out.File
	file_cybermetrica_proto_goTypes = nil
	file_cybermetrica_proto_depIdxs = nil
}
