// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: cyber.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_UNKNOWN  Status = 0
	Status_ACTIVE   Status = 1
	Status_INACTIVE Status = 2
	Status_OK       Status = 3
	Status_ERROR    Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "ACTIVE",
		2: "INACTIVE",
		3: "OK",
		4: "ERROR",
	}
	Status_value = map[string]int32{
		"UNKNOWN":  0,
		"ACTIVE":   1,
		"INACTIVE": 2,
		"OK":       3,
		"ERROR":    4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_cyber_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_cyber_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_cyber_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_cyber_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_cyber_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_cyber_proto_rawDescGZIP(), []int{0}
}

type StatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=cybertele.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReply) Reset() {
	*x = StatusReply{}
	mi := &file_cyber_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReply) ProtoMessage() {}

func (x *StatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_cyber_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReply.ProtoReflect.Descriptor instead.
func (*StatusReply) Descriptor() ([]byte, []int) {
	return file_cyber_proto_rawDescGZIP(), []int{1}
}

func (x *StatusReply) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNKNOWN
}

type Disk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	All           float32                `protobuf:"fixed32,1,opt,name=all,proto3" json:"all,omitempty"`
	Used          float32                `protobuf:"fixed32,2,opt,name=used,proto3" json:"used,omitempty"`
	Free          float32                `protobuf:"fixed32,3,opt,name=free,proto3" json:"free,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disk) Reset() {
	*x = Disk{}
	mi := &file_cyber_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disk) ProtoMessage() {}

func (x *Disk) ProtoReflect() protoreflect.Message {
	mi := &file_cyber_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disk.ProtoReflect.Descriptor instead.
func (*Disk) Descriptor() ([]byte, []int) {
	return file_cyber_proto_rawDescGZIP(), []int{2}
}

func (x *Disk) GetAll() float32 {
	if x != nil {
		return x.All
	}
	return 0
}

func (x *Disk) GetUsed() float32 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *Disk) GetFree() float32 {
	if x != nil {
		return x.Free
	}
	return 0
}

type HealthReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Postgres      Status                 `protobuf:"varint,1,opt,name=postgres,proto3,enum=cybertele.Status" json:"postgres,omitempty"`
	Mongo         Status                 `protobuf:"varint,2,opt,name=mongo,proto3,enum=cybertele.Status" json:"mongo,omitempty"`
	Parser        Status                 `protobuf:"varint,3,opt,name=parser,proto3,enum=cybertele.Status" json:"parser,omitempty"`
	Disk          *Disk                  `protobuf:"bytes,4,opt,name=disk,proto3" json:"disk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthReply) Reset() {
	*x = HealthReply{}
	mi := &file_cyber_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReply) ProtoMessage() {}

func (x *HealthReply) ProtoReflect() protoreflect.Message {
	mi := &file_cyber_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReply.ProtoReflect.Descriptor instead.
func (*HealthReply) Descriptor() ([]byte, []int) {
	return file_cyber_proto_rawDescGZIP(), []int{3}
}

func (x *HealthReply) GetPostgres() Status {
	if x != nil {
		return x.Postgres
	}
	return Status_UNKNOWN
}

func (x *HealthReply) GetMongo() Status {
	if x != nil {
		return x.Mongo
	}
	return Status_UNKNOWN
}

func (x *HealthReply) GetParser() Status {
	if x != nil {
		return x.Parser
	}
	return Status_UNKNOWN
}

func (x *HealthReply) GetDisk() *Disk {
	if x != nil {
		return x.Disk
	}
	return nil
}

type ParserStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parser        Status                 `protobuf:"varint,1,opt,name=parser,proto3,enum=cybertele.Status" json:"parser,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParserStatus) Reset() {
	*x = ParserStatus{}
	mi := &file_cyber_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParserStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParserStatus) ProtoMessage() {}

func (x *ParserStatus) ProtoReflect() protoreflect.Message {
	mi := &file_cyber_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParserStatus.ProtoReflect.Descriptor instead.
func (*ParserStatus) Descriptor() ([]byte, []int) {
	return file_cyber_proto_rawDescGZIP(), []int{4}
}

func (x *ParserStatus) GetParser() Status {
	if x != nil {
		return x.Parser
	}
	return Status_UNKNOWN
}

func (x *ParserStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Sn            string                 `protobuf:"bytes,3,opt,name=sn,proto3" json:"sn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_cyber_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cyber_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_cyber_proto_rawDescGZIP(), []int{5}
}

func (x *PageRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PageRequest) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_cyber_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_cyber_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_cyber_proto_rawDescGZIP(), []int{6}
}

func (x *Pagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Pagination) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Machine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            string                 `protobuf:"bytes,1,opt,name=sn,proto3" json:"sn,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Sync          bool                   `protobuf:"varint,3,opt,name=sync,proto3" json:"sync,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Machine) Reset() {
	*x = Machine{}
	mi := &file_cyber_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Machine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Machine) ProtoMessage() {}

func (x *Machine) ProtoReflect() protoreflect.Message {
	mi := &file_cyber_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Machine.ProtoReflect.Descriptor instead.
func (*Machine) Descriptor() ([]byte, []int) {
	return file_cyber_proto_rawDescGZIP(), []int{7}
}

func (x *Machine) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *Machine) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Machine) GetSync() bool {
	if x != nil {
		return x.Sync
	}
	return false
}

type Machines struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Machines      []*Machine             `protobuf:"bytes,1,rep,name=machines,proto3" json:"machines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Machines) Reset() {
	*x = Machines{}
	mi := &file_cyber_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Machines) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Machines) ProtoMessage() {}

func (x *Machines) ProtoReflect() protoreflect.Message {
	mi := &file_cyber_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Machines.ProtoReflect.Descriptor instead.
func (*Machines) Descriptor() ([]byte, []int) {
	return file_cyber_proto_rawDescGZIP(), []int{8}
}

func (x *Machines) GetMachines() []*Machine {
	if x != nil {
		return x.Machines
	}
	return nil
}

type DataType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Meaning       string                 `protobuf:"bytes,3,opt,name=meaning,proto3" json:"meaning,omitempty"`
	Required      bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataType) Reset() {
	*x = DataType{}
	mi := &file_cyber_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType) ProtoMessage() {}

func (x *DataType) ProtoReflect() protoreflect.Message {
	mi := &file_cyber_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType.ProtoReflect.Descriptor instead.
func (*DataType) Descriptor() ([]byte, []int) {
	return file_cyber_proto_rawDescGZIP(), []int{9}
}

func (x *DataType) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DataType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataType) GetMeaning() string {
	if x != nil {
		return x.Meaning
	}
	return ""
}

func (x *DataType) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

type DataTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*DataType            `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataTypes) Reset() {
	*x = DataTypes{}
	mi := &file_cyber_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataTypes) ProtoMessage() {}

func (x *DataTypes) ProtoReflect() protoreflect.Message {
	mi := &file_cyber_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataTypes.ProtoReflect.Descriptor instead.
func (*DataTypes) Descriptor() ([]byte, []int) {
	return file_cyber_proto_rawDescGZIP(), []int{10}
}

func (x *DataTypes) GetData() []*DataType {
	if x != nil {
		return x.Data
	}
	return nil
}

type ModelDataTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	DataTypes     []*DataType            `protobuf:"bytes,2,rep,name=dataTypes,proto3" json:"dataTypes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelDataTypes) Reset() {
	*x = ModelDataTypes{}
	mi := &file_cyber_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelDataTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelDataTypes) ProtoMessage() {}

func (x *ModelDataTypes) ProtoReflect() protoreflect.Message {
	mi := &file_cyber_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelDataTypes.ProtoReflect.Descriptor instead.
func (*ModelDataTypes) Descriptor() ([]byte, []int) {
	return file_cyber_proto_rawDescGZIP(), []int{11}
}

func (x *ModelDataTypes) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ModelDataTypes) GetDataTypes() []*DataType {
	if x != nil {
		return x.DataTypes
	}
	return nil
}

type AllModelsDataTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*ModelDataTypes      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllModelsDataTypes) Reset() {
	*x = AllModelsDataTypes{}
	mi := &file_cyber_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllModelsDataTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllModelsDataTypes) ProtoMessage() {}

func (x *AllModelsDataTypes) ProtoReflect() protoreflect.Message {
	mi := &file_cyber_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllModelsDataTypes.ProtoReflect.Descriptor instead.
func (*AllModelsDataTypes) Descriptor() ([]byte, []int) {
	return file_cyber_proto_rawDescGZIP(), []int{12}
}

func (x *AllModelsDataTypes) GetData() []*ModelDataTypes {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_cyber_proto protoreflect.FileDescriptor

const file_cyber_proto_rawDesc = "" +
	"\n" +
	"\vcyber.proto\x12\tcybertele\"\a\n" +
	"\x05Empty\"8\n" +
	"\vStatusReply\x12)\n" +
	"\x06status\x18\x01 \x01(\x0e2\x11.cybertele.StatusR\x06status\"@\n" +
	"\x04Disk\x12\x10\n" +
	"\x03all\x18\x01 \x01(\x02R\x03all\x12\x12\n" +
	"\x04used\x18\x02 \x01(\x02R\x04used\x12\x12\n" +
	"\x04free\x18\x03 \x01(\x02R\x04free\"\xb5\x01\n" +
	"\vHealthReply\x12-\n" +
	"\bpostgres\x18\x01 \x01(\x0e2\x11.cybertele.StatusR\bpostgres\x12'\n" +
	"\x05mongo\x18\x02 \x01(\x0e2\x11.cybertele.StatusR\x05mongo\x12)\n" +
	"\x06parser\x18\x03 \x01(\x0e2\x11.cybertele.StatusR\x06parser\x12#\n" +
	"\x04disk\x18\x04 \x01(\v2\x0f.cybertele.DiskR\x04disk\"S\n" +
	"\fParserStatus\x12)\n" +
	"\x06parser\x18\x01 \x01(\x0e2\x11.cybertele.StatusR\x06parser\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"G\n" +
	"\vPageRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x0e\n" +
	"\x02sn\x18\x03 \x01(\tR\x02sn\"L\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\"C\n" +
	"\aMachine\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\tR\x02sn\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x12\n" +
	"\x04sync\x18\x03 \x01(\bR\x04sync\":\n" +
	"\bMachines\x12.\n" +
	"\bmachines\x18\x01 \x03(\v2\x12.cybertele.MachineR\bmachines\"h\n" +
	"\bDataType\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\ameaning\x18\x03 \x01(\tR\ameaning\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\"4\n" +
	"\tDataTypes\x12'\n" +
	"\x04data\x18\x01 \x03(\v2\x13.cybertele.DataTypeR\x04data\"Y\n" +
	"\x0eModelDataTypes\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x121\n" +
	"\tdataTypes\x18\x02 \x03(\v2\x13.cybertele.DataTypeR\tdataTypes\"C\n" +
	"\x12AllModelsDataTypes\x12-\n" +
	"\x04data\x18\x01 \x03(\v2\x19.cybertele.ModelDataTypesR\x04data*B\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\f\n" +
	"\bINACTIVE\x10\x02\x12\x06\n" +
	"\x02OK\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x04B\tZ\a./protob\x06proto3"

var (
	file_cyber_proto_rawDescOnce sync.Once
	file_cyber_proto_rawDescData []byte
)

func file_cyber_proto_rawDescGZIP() []byte {
	file_cyber_proto_rawDescOnce.Do(func() {
		file_cyber_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cyber_proto_rawDesc), len(file_cyber_proto_rawDesc)))
	})
	return file_cyber_proto_rawDescData
}

var file_cyber_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cyber_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_cyber_proto_goTypes = []any{
	(Status)(0),                // 0: cybertele.Status
	(*Empty)(nil),              // 1: cybertele.Empty
	(*StatusReply)(nil),        // 2: cybertele.StatusReply
	(*Disk)(nil),               // 3: cybertele.Disk
	(*HealthReply)(nil),        // 4: cybertele.HealthReply
	(*ParserStatus)(nil),       // 5: cybertele.ParserStatus
	(*PageRequest)(nil),        // 6: cybertele.PageRequest
	(*Pagination)(nil),         // 7: cybertele.Pagination
	(*Machine)(nil),            // 8: cybertele.Machine
	(*Machines)(nil),           // 9: cybertele.Machines
	(*DataType)(nil),           // 10: cybertele.DataType
	(*DataTypes)(nil),          // 11: cybertele.DataTypes
	(*ModelDataTypes)(nil),     // 12: cybertele.ModelDataTypes
	(*AllModelsDataTypes)(nil), // 13: cybertele.AllModelsDataTypes
}
var file_cyber_proto_depIdxs = []int32{
	0,  // 0: cybertele.StatusReply.status:type_name -> cybertele.Status
	0,  // 1: cybertele.HealthReply.postgres:type_name -> cybertele.Status
	0,  // 2: cybertele.HealthReply.mongo:type_name -> cybertele.Status
	0,  // 3: cybertele.HealthReply.parser:type_name -> cybertele.Status
	3,  // 4: cybertele.HealthReply.disk:type_name -> cybertele.Disk
	0,  // 5: cybertele.ParserStatus.parser:type_name -> cybertele.Status
	8,  // 6: cybertele.Machines.machines:type_name -> cybertele.Machine
	10, // 7: cybertele.DataTypes.data:type_name -> cybertele.DataType
	10, // 8: cybertele.ModelDataTypes.dataTypes:type_name -> cybertele.DataType
	12, // 9: cybertele.AllModelsDataTypes.data:type_name -> cybertele.ModelDataTypes
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_cyber_proto_init() }
func file_cyber_proto_init() {
	if File_cyber_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cyber_proto_rawDesc), len(file_cyber_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cyber_proto_goTypes,
		DependencyIndexes: file_cyber_proto_depIdxs,
		EnumInfos:         file_cyber_proto_enumTypes,
		MessageInfos:      file_cyber_proto_msgTypes,
	}.Build()
	File_cyber_proto = out.File
	file_cyber_proto_goTypes = nil
	file_cyber_proto_depIdxs = nil
}
