// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: cybermetrica.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Cybermetrica_Health_FullMethodName               = "/cybertele.Cybermetrica/Health"
	Cybermetrica_ParserState_FullMethodName          = "/cybertele.Cybermetrica/ParserState"
	Cybermetrica_ParserStart_FullMethodName          = "/cybertele.Cybermetrica/ParserStart"
	Cybermetrica_ParserStop_FullMethodName           = "/cybertele.Cybermetrica/ParserStop"
	Cybermetrica_ParserLogs_FullMethodName           = "/cybertele.Cybermetrica/ParserLogs"
	Cybermetrica_MachineLogs_FullMethodName          = "/cybertele.Cybermetrica/MachineLogs"
	Cybermetrica_MachineDataTypes_FullMethodName     = "/cybertele.Cybermetrica/MachineDataTypes"
	Cybermetrica_MachineDayStatistic_FullMethodName  = "/cybertele.Cybermetrica/MachineDayStatistic"
	Cybermetrica_MachineDaysStatistic_FullMethodName = "/cybertele.Cybermetrica/MachineDaysStatistic"
	Cybermetrica_MachineErrors_FullMethodName        = "/cybertele.Cybermetrica/MachineErrors"
	Cybermetrica_MachineGraph_FullMethodName         = "/cybertele.Cybermetrica/MachineGraph"
	Cybermetrica_MachineGps_FullMethodName           = "/cybertele.Cybermetrica/MachineGps"
	Cybermetrica_AllDataTypes_FullMethodName         = "/cybertele.Cybermetrica/AllDataTypes"
)

// CybermetricaClient is the client API for Cybermetrica service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CybermetricaClient interface {
	Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthReply, error)
	ParserState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ParserStatus, error)
	ParserStart(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ParserStatus, error)
	ParserStop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ParserStatus, error)
	ParserLogs(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*ParserMetricaLogsReply, error)
	MachineLogs(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*ParserMetricaLogsReply, error)
	MachineDataTypes(ctx context.Context, in *Machine, opts ...grpc.CallOption) (*MachineDataTypesReply, error)
	MachineDayStatistic(ctx context.Context, in *MachineStatisticRequest, opts ...grpc.CallOption) (*DayData, error)
	MachineDaysStatistic(ctx context.Context, in *MachineStatisticRequest, opts ...grpc.CallOption) (*DaysData, error)
	MachineErrors(ctx context.Context, in *MachineStatisticRequest, opts ...grpc.CallOption) (*MachineErrorsReply, error)
	MachineGraph(ctx context.Context, in *MachineStatisticRequest, opts ...grpc.CallOption) (*GraphData, error)
	MachineGps(ctx context.Context, in *MachineStatisticRequest, opts ...grpc.CallOption) (*GpsData, error)
	AllDataTypes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DataTypes, error)
}

type cybermetricaClient struct {
	cc grpc.ClientConnInterface
}

func NewCybermetricaClient(cc grpc.ClientConnInterface) CybermetricaClient {
	return &cybermetricaClient{cc}
}

func (c *cybermetricaClient) Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthReply)
	err := c.cc.Invoke(ctx, Cybermetrica_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cybermetricaClient) ParserState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ParserStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParserStatus)
	err := c.cc.Invoke(ctx, Cybermetrica_ParserState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cybermetricaClient) ParserStart(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ParserStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParserStatus)
	err := c.cc.Invoke(ctx, Cybermetrica_ParserStart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cybermetricaClient) ParserStop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ParserStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParserStatus)
	err := c.cc.Invoke(ctx, Cybermetrica_ParserStop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cybermetricaClient) ParserLogs(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*ParserMetricaLogsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParserMetricaLogsReply)
	err := c.cc.Invoke(ctx, Cybermetrica_ParserLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cybermetricaClient) MachineLogs(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*ParserMetricaLogsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParserMetricaLogsReply)
	err := c.cc.Invoke(ctx, Cybermetrica_MachineLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cybermetricaClient) MachineDataTypes(ctx context.Context, in *Machine, opts ...grpc.CallOption) (*MachineDataTypesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MachineDataTypesReply)
	err := c.cc.Invoke(ctx, Cybermetrica_MachineDataTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cybermetricaClient) MachineDayStatistic(ctx context.Context, in *MachineStatisticRequest, opts ...grpc.CallOption) (*DayData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DayData)
	err := c.cc.Invoke(ctx, Cybermetrica_MachineDayStatistic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cybermetricaClient) MachineDaysStatistic(ctx context.Context, in *MachineStatisticRequest, opts ...grpc.CallOption) (*DaysData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DaysData)
	err := c.cc.Invoke(ctx, Cybermetrica_MachineDaysStatistic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cybermetricaClient) MachineErrors(ctx context.Context, in *MachineStatisticRequest, opts ...grpc.CallOption) (*MachineErrorsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MachineErrorsReply)
	err := c.cc.Invoke(ctx, Cybermetrica_MachineErrors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cybermetricaClient) MachineGraph(ctx context.Context, in *MachineStatisticRequest, opts ...grpc.CallOption) (*GraphData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GraphData)
	err := c.cc.Invoke(ctx, Cybermetrica_MachineGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cybermetricaClient) MachineGps(ctx context.Context, in *MachineStatisticRequest, opts ...grpc.CallOption) (*GpsData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GpsData)
	err := c.cc.Invoke(ctx, Cybermetrica_MachineGps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cybermetricaClient) AllDataTypes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DataTypes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataTypes)
	err := c.cc.Invoke(ctx, Cybermetrica_AllDataTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CybermetricaServer is the server API for Cybermetrica service.
// All implementations must embed UnimplementedCybermetricaServer
// for forward compatibility.
type CybermetricaServer interface {
	Health(context.Context, *Empty) (*HealthReply, error)
	ParserState(context.Context, *Empty) (*ParserStatus, error)
	ParserStart(context.Context, *Empty) (*ParserStatus, error)
	ParserStop(context.Context, *Empty) (*ParserStatus, error)
	ParserLogs(context.Context, *PageRequest) (*ParserMetricaLogsReply, error)
	MachineLogs(context.Context, *PageRequest) (*ParserMetricaLogsReply, error)
	MachineDataTypes(context.Context, *Machine) (*MachineDataTypesReply, error)
	MachineDayStatistic(context.Context, *MachineStatisticRequest) (*DayData, error)
	MachineDaysStatistic(context.Context, *MachineStatisticRequest) (*DaysData, error)
	MachineErrors(context.Context, *MachineStatisticRequest) (*MachineErrorsReply, error)
	MachineGraph(context.Context, *MachineStatisticRequest) (*GraphData, error)
	MachineGps(context.Context, *MachineStatisticRequest) (*GpsData, error)
	AllDataTypes(context.Context, *Empty) (*DataTypes, error)
	mustEmbedUnimplementedCybermetricaServer()
}

// UnimplementedCybermetricaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCybermetricaServer struct{}

func (UnimplementedCybermetricaServer) Health(context.Context, *Empty) (*HealthReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedCybermetricaServer) ParserState(context.Context, *Empty) (*ParserStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method ParserState not implemented")
}
func (UnimplementedCybermetricaServer) ParserStart(context.Context, *Empty) (*ParserStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method ParserStart not implemented")
}
func (UnimplementedCybermetricaServer) ParserStop(context.Context, *Empty) (*ParserStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method ParserStop not implemented")
}
func (UnimplementedCybermetricaServer) ParserLogs(context.Context, *PageRequest) (*ParserMetricaLogsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ParserLogs not implemented")
}
func (UnimplementedCybermetricaServer) MachineLogs(context.Context, *PageRequest) (*ParserMetricaLogsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method MachineLogs not implemented")
}
func (UnimplementedCybermetricaServer) MachineDataTypes(context.Context, *Machine) (*MachineDataTypesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method MachineDataTypes not implemented")
}
func (UnimplementedCybermetricaServer) MachineDayStatistic(context.Context, *MachineStatisticRequest) (*DayData, error) {
	return nil, status.Error(codes.Unimplemented, "method MachineDayStatistic not implemented")
}
func (UnimplementedCybermetricaServer) MachineDaysStatistic(context.Context, *MachineStatisticRequest) (*DaysData, error) {
	return nil, status.Error(codes.Unimplemented, "method MachineDaysStatistic not implemented")
}
func (UnimplementedCybermetricaServer) MachineErrors(context.Context, *MachineStatisticRequest) (*MachineErrorsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method MachineErrors not implemented")
}
func (UnimplementedCybermetricaServer) MachineGraph(context.Context, *MachineStatisticRequest) (*GraphData, error) {
	return nil, status.Error(codes.Unimplemented, "method MachineGraph not implemented")
}
func (UnimplementedCybermetricaServer) MachineGps(context.Context, *MachineStatisticRequest) (*GpsData, error) {
	return nil, status.Error(codes.Unimplemented, "method MachineGps not implemented")
}
func (UnimplementedCybermetricaServer) AllDataTypes(context.Context, *Empty) (*DataTypes, error) {
	return nil, status.Error(codes.Unimplemented, "method AllDataTypes not implemented")
}
func (UnimplementedCybermetricaServer) mustEmbedUnimplementedCybermetricaServer() {}
func (UnimplementedCybermetricaServer) testEmbeddedByValue()                      {}

// UnsafeCybermetricaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CybermetricaServer will
// result in compilation errors.
type UnsafeCybermetricaServer interface {
	mustEmbedUnimplementedCybermetricaServer()
}

func RegisterCybermetricaServer(s grpc.ServiceRegistrar, srv CybermetricaServer) {
	// If the following call panics, it indicates UnimplementedCybermetricaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Cybermetrica_ServiceDesc, srv)
}

func _Cybermetrica_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybermetricaServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cybermetrica_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybermetricaServer).Health(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cybermetrica_ParserState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybermetricaServer).ParserState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cybermetrica_ParserState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybermetricaServer).ParserState(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cybermetrica_ParserStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybermetricaServer).ParserStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cybermetrica_ParserStart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybermetricaServer).ParserStart(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cybermetrica_ParserStop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybermetricaServer).ParserStop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cybermetrica_ParserStop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybermetricaServer).ParserStop(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cybermetrica_ParserLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybermetricaServer).ParserLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cybermetrica_ParserLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybermetricaServer).ParserLogs(ctx, req.(*PageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cybermetrica_MachineLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybermetricaServer).MachineLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cybermetrica_MachineLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybermetricaServer).MachineLogs(ctx, req.(*PageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cybermetrica_MachineDataTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Machine)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybermetricaServer).MachineDataTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cybermetrica_MachineDataTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybermetricaServer).MachineDataTypes(ctx, req.(*Machine))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cybermetrica_MachineDayStatistic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MachineStatisticRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybermetricaServer).MachineDayStatistic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cybermetrica_MachineDayStatistic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybermetricaServer).MachineDayStatistic(ctx, req.(*MachineStatisticRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cybermetrica_MachineDaysStatistic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MachineStatisticRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybermetricaServer).MachineDaysStatistic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cybermetrica_MachineDaysStatistic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybermetricaServer).MachineDaysStatistic(ctx, req.(*MachineStatisticRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cybermetrica_MachineErrors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MachineStatisticRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybermetricaServer).MachineErrors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cybermetrica_MachineErrors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybermetricaServer).MachineErrors(ctx, req.(*MachineStatisticRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cybermetrica_MachineGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MachineStatisticRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybermetricaServer).MachineGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cybermetrica_MachineGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybermetricaServer).MachineGraph(ctx, req.(*MachineStatisticRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cybermetrica_MachineGps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MachineStatisticRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybermetricaServer).MachineGps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cybermetrica_MachineGps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybermetricaServer).MachineGps(ctx, req.(*MachineStatisticRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cybermetrica_AllDataTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CybermetricaServer).AllDataTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cybermetrica_AllDataTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CybermetricaServer).AllDataTypes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Cybermetrica_ServiceDesc is the grpc.ServiceDesc for Cybermetrica service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cybermetrica_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cybertele.Cybermetrica",
	HandlerType: (*CybermetricaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _Cybermetrica_Health_Handler,
		},
		{
			MethodName: "ParserState",
			Handler:    _Cybermetrica_ParserState_Handler,
		},
		{
			MethodName: "ParserStart",
			Handler:    _Cybermetrica_ParserStart_Handler,
		},
		{
			MethodName: "ParserStop",
			Handler:    _Cybermetrica_ParserStop_Handler,
		},
		{
			MethodName: "ParserLogs",
			Handler:    _Cybermetrica_ParserLogs_Handler,
		},
		{
			MethodName: "MachineLogs",
			Handler:    _Cybermetrica_MachineLogs_Handler,
		},
		{
			MethodName: "MachineDataTypes",
			Handler:    _Cybermetrica_MachineDataTypes_Handler,
		},
		{
			MethodName: "MachineDayStatistic",
			Handler:    _Cybermetrica_MachineDayStatistic_Handler,
		},
		{
			MethodName: "MachineDaysStatistic",
			Handler:    _Cybermetrica_MachineDaysStatistic_Handler,
		},
		{
			MethodName: "MachineErrors",
			Handler:    _Cybermetrica_MachineErrors_Handler,
		},
		{
			MethodName: "MachineGraph",
			Handler:    _Cybermetrica_MachineGraph_Handler,
		},
		{
			MethodName: "MachineGps",
			Handler:    _Cybermetrica_MachineGps_Handler,
		},
		{
			MethodName: "AllDataTypes",
			Handler:    _Cybermetrica_AllDataTypes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cybermetrica.proto",
}
