// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: portalclient.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncOffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*SyncOffMessage      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncOffRequest) Reset() {
	*x = SyncOffRequest{}
	mi := &file_portalclient_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncOffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncOffRequest) ProtoMessage() {}

func (x *SyncOffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portalclient_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncOffRequest.ProtoReflect.Descriptor instead.
func (*SyncOffRequest) Descriptor() ([]byte, []int) {
	return file_portalclient_proto_rawDescGZIP(), []int{0}
}

func (x *SyncOffRequest) GetData() []*SyncOffMessage {
	if x != nil {
		return x.Data
	}
	return nil
}

type SyncOffMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            int32                  `protobuf:"varint,1,opt,name=sn,proto3" json:"sn,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncOffMessage) Reset() {
	*x = SyncOffMessage{}
	mi := &file_portalclient_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncOffMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncOffMessage) ProtoMessage() {}

func (x *SyncOffMessage) ProtoReflect() protoreflect.Message {
	mi := &file_portalclient_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncOffMessage.ProtoReflect.Descriptor instead.
func (*SyncOffMessage) Descriptor() ([]byte, []int) {
	return file_portalclient_proto_rawDescGZIP(), []int{1}
}

func (x *SyncOffMessage) GetSn() int32 {
	if x != nil {
		return x.Sn
	}
	return 0
}

func (x *SyncOffMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_portalclient_proto protoreflect.FileDescriptor

const file_portalclient_proto_rawDesc = "" +
	"\n" +
	"\x12portalclient.proto\x12\tcybertele\x1a\vcyber.proto\"?\n" +
	"\x0eSyncOffRequest\x12-\n" +
	"\x04data\x18\x01 \x03(\v2\x19.cybertele.SyncOffMessageR\x04data\":\n" +
	"\x0eSyncOffMessage\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\x05R\x02sn\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xe3\x02\n" +
	"\fPortalClient\x12=\n" +
	"\x12GetMetricaMachines\x12\x10.cybertele.Empty\x1a\x13.cybertele.Machines\"\x00\x12N\n" +
	"\x19GetMetricaModelsDataTypes\x12\x10.cybertele.Empty\x1a\x1d.cybertele.AllModelsDataTypes\"\x00\x129\n" +
	"\x0eGetMapMachines\x12\x10.cybertele.Empty\x1a\x13.cybertele.Machines\"\x00\x12E\n" +
	"\x14OffMeticaMachineSync\x12\x19.cybertele.SyncOffRequest\x1a\x10.cybertele.Empty\"\x00\x12B\n" +
	"\x11OffMapMachineSync\x12\x19.cybertele.SyncOffRequest\x1a\x10.cybertele.Empty\"\x00B\tZ\a./protob\x06proto3"

var (
	file_portalclient_proto_rawDescOnce sync.Once
	file_portalclient_proto_rawDescData []byte
)

func file_portalclient_proto_rawDescGZIP() []byte {
	file_portalclient_proto_rawDescOnce.Do(func() {
		file_portalclient_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_portalclient_proto_rawDesc), len(file_portalclient_proto_rawDesc)))
	})
	return file_portalclient_proto_rawDescData
}

var file_portalclient_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_portalclient_proto_goTypes = []any{
	(*SyncOffRequest)(nil),     // 0: cybertele.SyncOffRequest
	(*SyncOffMessage)(nil),     // 1: cybertele.SyncOffMessage
	(*Empty)(nil),              // 2: cybertele.Empty
	(*Machines)(nil),           // 3: cybertele.Machines
	(*AllModelsDataTypes)(nil), // 4: cybertele.AllModelsDataTypes
}
var file_portalclient_proto_depIdxs = []int32{
	1, // 0: cybertele.SyncOffRequest.data:type_name -> cybertele.SyncOffMessage
	2, // 1: cybertele.PortalClient.GetMetricaMachines:input_type -> cybertele.Empty
	2, // 2: cybertele.PortalClient.GetMetricaModelsDataTypes:input_type -> cybertele.Empty
	2, // 3: cybertele.PortalClient.GetMapMachines:input_type -> cybertele.Empty
	0, // 4: cybertele.PortalClient.OffMeticaMachineSync:input_type -> cybertele.SyncOffRequest
	0, // 5: cybertele.PortalClient.OffMapMachineSync:input_type -> cybertele.SyncOffRequest
	3, // 6: cybertele.PortalClient.GetMetricaMachines:output_type -> cybertele.Machines
	4, // 7: cybertele.PortalClient.GetMetricaModelsDataTypes:output_type -> cybertele.AllModelsDataTypes
	3, // 8: cybertele.PortalClient.GetMapMachines:output_type -> cybertele.Machines
	2, // 9: cybertele.PortalClient.OffMeticaMachineSync:output_type -> cybertele.Empty
	2, // 10: cybertele.PortalClient.OffMapMachineSync:output_type -> cybertele.Empty
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_portalclient_proto_init() }
func file_portalclient_proto_init() {
	if File_portalclient_proto != nil {
		return
	}
	file_cyber_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_portalclient_proto_rawDesc), len(file_portalclient_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_portalclient_proto_goTypes,
		DependencyIndexes: file_portalclient_proto_depIdxs,
		MessageInfos:      file_portalclient_proto_msgTypes,
	}.Build()
	File_portalclient_proto = out.File
	file_portalclient_proto_goTypes = nil
	file_portalclient_proto_depIdxs = nil
}
