// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: portalclient.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PortalClient_GetMetricaMachines_FullMethodName        = "/cybertele.PortalClient/GetMetricaMachines"
	PortalClient_GetMetricaModelsDataTypes_FullMethodName = "/cybertele.PortalClient/GetMetricaModelsDataTypes"
	PortalClient_GetMapMachines_FullMethodName            = "/cybertele.PortalClient/GetMapMachines"
	PortalClient_OffMeticaMachineSync_FullMethodName      = "/cybertele.PortalClient/OffMeticaMachineSync"
	PortalClient_OffMapMachineSync_FullMethodName         = "/cybertele.PortalClient/OffMapMachineSync"
)

// PortalClientClient is the client API for PortalClient service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PortalClientClient interface {
	GetMetricaMachines(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Machines, error)
	GetMetricaModelsDataTypes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AllModelsDataTypes, error)
	GetMapMachines(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Machines, error)
	OffMeticaMachineSync(ctx context.Context, in *SyncOffRequest, opts ...grpc.CallOption) (*Empty, error)
	OffMapMachineSync(ctx context.Context, in *SyncOffRequest, opts ...grpc.CallOption) (*Empty, error)
}

type portalClientClient struct {
	cc grpc.ClientConnInterface
}

func NewPortalClientClient(cc grpc.ClientConnInterface) PortalClientClient {
	return &portalClientClient{cc}
}

func (c *portalClientClient) GetMetricaMachines(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Machines, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Machines)
	err := c.cc.Invoke(ctx, PortalClient_GetMetricaMachines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portalClientClient) GetMetricaModelsDataTypes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AllModelsDataTypes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllModelsDataTypes)
	err := c.cc.Invoke(ctx, PortalClient_GetMetricaModelsDataTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portalClientClient) GetMapMachines(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Machines, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Machines)
	err := c.cc.Invoke(ctx, PortalClient_GetMapMachines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portalClientClient) OffMeticaMachineSync(ctx context.Context, in *SyncOffRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PortalClient_OffMeticaMachineSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portalClientClient) OffMapMachineSync(ctx context.Context, in *SyncOffRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PortalClient_OffMapMachineSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortalClientServer is the server API for PortalClient service.
// All implementations must embed UnimplementedPortalClientServer
// for forward compatibility.
type PortalClientServer interface {
	GetMetricaMachines(context.Context, *Empty) (*Machines, error)
	GetMetricaModelsDataTypes(context.Context, *Empty) (*AllModelsDataTypes, error)
	GetMapMachines(context.Context, *Empty) (*Machines, error)
	OffMeticaMachineSync(context.Context, *SyncOffRequest) (*Empty, error)
	OffMapMachineSync(context.Context, *SyncOffRequest) (*Empty, error)
	mustEmbedUnimplementedPortalClientServer()
}

// UnimplementedPortalClientServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPortalClientServer struct{}

func (UnimplementedPortalClientServer) GetMetricaMachines(context.Context, *Empty) (*Machines, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetricaMachines not implemented")
}
func (UnimplementedPortalClientServer) GetMetricaModelsDataTypes(context.Context, *Empty) (*AllModelsDataTypes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetricaModelsDataTypes not implemented")
}
func (UnimplementedPortalClientServer) GetMapMachines(context.Context, *Empty) (*Machines, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMapMachines not implemented")
}
func (UnimplementedPortalClientServer) OffMeticaMachineSync(context.Context, *SyncOffRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method OffMeticaMachineSync not implemented")
}
func (UnimplementedPortalClientServer) OffMapMachineSync(context.Context, *SyncOffRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method OffMapMachineSync not implemented")
}
func (UnimplementedPortalClientServer) mustEmbedUnimplementedPortalClientServer() {}
func (UnimplementedPortalClientServer) testEmbeddedByValue()                      {}

// UnsafePortalClientServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PortalClientServer will
// result in compilation errors.
type UnsafePortalClientServer interface {
	mustEmbedUnimplementedPortalClientServer()
}

func RegisterPortalClientServer(s grpc.ServiceRegistrar, srv PortalClientServer) {
	// If the following call panics, it indicates UnimplementedPortalClientServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PortalClient_ServiceDesc, srv)
}

func _PortalClient_GetMetricaMachines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortalClientServer).GetMetricaMachines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortalClient_GetMetricaMachines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortalClientServer).GetMetricaMachines(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortalClient_GetMetricaModelsDataTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortalClientServer).GetMetricaModelsDataTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortalClient_GetMetricaModelsDataTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortalClientServer).GetMetricaModelsDataTypes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortalClient_GetMapMachines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortalClientServer).GetMapMachines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortalClient_GetMapMachines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortalClientServer).GetMapMachines(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortalClient_OffMeticaMachineSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncOffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortalClientServer).OffMeticaMachineSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortalClient_OffMeticaMachineSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortalClientServer).OffMeticaMachineSync(ctx, req.(*SyncOffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortalClient_OffMapMachineSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncOffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortalClientServer).OffMapMachineSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortalClient_OffMapMachineSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortalClientServer).OffMapMachineSync(ctx, req.(*SyncOffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PortalClient_ServiceDesc is the grpc.ServiceDesc for PortalClient service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PortalClient_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cybertele.PortalClient",
	HandlerType: (*PortalClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetricaMachines",
			Handler:    _PortalClient_GetMetricaMachines_Handler,
		},
		{
			MethodName: "GetMetricaModelsDataTypes",
			Handler:    _PortalClient_GetMetricaModelsDataTypes_Handler,
		},
		{
			MethodName: "GetMapMachines",
			Handler:    _PortalClient_GetMapMachines_Handler,
		},
		{
			MethodName: "OffMeticaMachineSync",
			Handler:    _PortalClient_OffMeticaMachineSync_Handler,
		},
		{
			MethodName: "OffMapMachineSync",
			Handler:    _PortalClient_OffMapMachineSync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "portalclient.proto",
}
